# Generated by Django 6.0.1 on 2026-01-27 21:02

from django.db import migrations

def convert_empty_strings_to_lists(apps, schema_editor):
    JobPosting = apps.get_model('core', 'JobPosting')
    
    # Convert all empty strings and existing text to empty lists
    for job in JobPosting.objects.all():
        job.responsibilities = [] if not job.responsibilities else []
        job.requirements = [] if not job.requirements else []
        job.nice_to_have = [] if not job.nice_to_have else []
        job.benefits = [] if not job.benefits else []
        job.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_jobposting_posted_by'),
    ]

    operations = [
        migrations.RunPython(convert_empty_strings_to_lists, migrations.RunPython.noop),
    ]
