# Generated by Django 6.0.1 on 2026-01-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_convert_text_to_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='benefits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='nice_to_have',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='requirements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='responsibilities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
