# Generated by Django 6.0.1 on 2026-01-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_jobposting_benefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
