# Generated by Django 6.0.1 on 2026-01-28 10:56

from django.db import migrations, models
import django.core.validators


def migrate_job_type_data(apps, schema_editor):
    """
    Migrate data from old structure to new structure:
    1. Copy job_type (employment type) to new employment_type field
    2. Convert is_remote/is_hybrid to new job_type (location type) field
    """
    JobPosting = apps.get_model('core', 'JobPosting')
    
    for job in JobPosting.objects.all():
        # Step 1: Copy old job_type to employment_type
        # The old job_type contained employment information (FULL_TIME, PART_TIME, etc.)
        job.employment_type = job.job_type
        
        # Step 2: Determine location type based on is_remote and is_hybrid flags
        if job.is_remote:
            job.job_type = 'REMOTE'
        elif job.is_hybrid:
            job.job_type = 'HYBRID'
        else:
            job.job_type = 'ON_SITE'
        
        job.save(update_fields=['employment_type', 'job_type'])


def reverse_migrate_job_type_data(apps, schema_editor):
    """
    Reverse migration: restore old structure from new structure
    """
    JobPosting = apps.get_model('core', 'JobPosting')
    
    for job in JobPosting.objects.all():
        # Restore old job_type from employment_type
        job.job_type = job.employment_type
        
        # Restore is_remote and is_hybrid flags
        if job.job_type == 'REMOTE':
            job.is_remote = True
            job.is_hybrid = False
        elif job.job_type == 'HYBRID':
            job.is_remote = False
            job.is_hybrid = True
        else:
            job.is_remote = False
            job.is_hybrid = False
        
        job.save(update_fields=['job_type', 'is_remote', 'is_hybrid'])



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_candidateprofile_is_verified'),
    ]

    operations = [
        # Step 1: Add new employment_type field (temporarily nullable)
        migrations.AddField(
            model_name='jobposting',
            name='employment_type',
            field=models.CharField(
                blank=True,
                null=True,
                max_length=20,
                choices=[
                    ('FULL_TIME', 'Full-time'),
                    ('PART_TIME', 'Part-time'),
                    ('CONTRACT', 'Contract'),
                    ('INTERNSHIP', 'Internship'),
                    ('FREELANCE', 'Freelance')
                ]
            ),
        ),
        
        # Step 2: Run data migration to copy old job_type to employment_type
        # and set new job_type based on is_remote/is_hybrid
        migrations.RunPython(
            migrate_job_type_data,
            reverse_migrate_job_type_data
        ),
        
        # Step 3: Alter job_type field to use LocationType choices
        migrations.AlterField(
            model_name='jobposting',
            name='job_type',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('REMOTE', 'Remote'),
                    ('ON_SITE', 'On-site'),
                    ('HYBRID', 'Hybrid')
                ]
            ),
        ),
        
        # Step 4: Make employment_type non-nullable after data migration
        migrations.AlterField(
            model_name='jobposting',
            name='employment_type',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('FULL_TIME', 'Full-time'),
                    ('PART_TIME', 'Part-time'),
                    ('CONTRACT', 'Contract'),
                    ('INTERNSHIP', 'Internship'),
                    ('FREELANCE', 'Freelance')
                ]
            ),
        ),
        
        # Step 5: Remove deprecated fields
        migrations.RemoveField(
            model_name='jobposting',
            name='is_remote',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='is_hybrid',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='number_of_positions',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='views_count',
        ),
        
        migrations.RemoveIndex(
            model_name='jobposting',
            name='core_jobpos_job_typ_755ce9_idx',  # <-- Correct index name
        ),

        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['job_type', 'experience_level'], name='job_type_exp_level_idx'),
        ),
    ]
