# Generated by Django 6.0.1 on 2026-01-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20260128_1056'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jobposting',
            new_name='core_jobpos_job_typ_755ce9_idx',
            old_name='job_type_exp_level_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('APPLICATION_STATUS', 'Application Status Update'), ('NEW_MESSAGE', 'New Message'), ('JOB_ALERT', 'Job Alert'), ('INTERVIEW', 'Interview Scheduled'), ('SYSTEM', 'System Notification'), ('APPLICATION', 'Application')], max_length=30),
        ),
    ]
