# Generated by Django 6.0.1 on 2026-01-28 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_job_type_exp_level_idx_core_jobpos_job_typ_755ce9_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyreview',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='companyreview',
            name='helpful_count',
        ),
        migrations.RemoveField(
            model_name='companyreview',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='companyreview',
            name='is_current_employee',
        ),
        migrations.RemoveField(
            model_name='companyreview',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='companyreview',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='companyreview',
            name='pros',
        ),
        migrations.RemoveField(
            model_name='companyreview',
            name='title',
        ),
    ]
