# Generated by Django 6.0.1 on 2026-01-31 20:02

import core.static_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_companyreview_cons_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, storage=core.static_backend.PrivateMediaStorage, upload_to='applications/resumes/'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=core.static_backend.PublicMediaStorage, upload_to='profiles/pictures'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, storage=core.static_backend.PrivateMediaStorage, upload_to='profiles/resumes'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, storage=core.static_backend.PublicMediaStorage, upload_to='companies/covers/'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=core.static_backend.PublicMediaStorage, upload_to='companies/logos/'),
        ),
    ]
