# Generated by Django 6.0.1 on 2026-02-04 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_application_resume_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="icon",
        ),
        migrations.CreateModel(
            name="JobNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_notifications",
                        to="core.candidateprofile",
                    ),
                ),
                (
                    "job_posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.jobposting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Notification",
                "verbose_name_plural": "Job Notifications",
                "ordering": ["-sent_at"],
                "indexes": [
                    models.Index(
                        fields=["candidate"], name="core_jobnot_candida_93cc41_idx"
                    ),
                    models.Index(
                        fields=["job_posting"], name="core_jobnot_job_pos_c24903_idx"
                    ),
                    models.Index(
                        fields=["sent_at"], name="core_jobnot_sent_at_489361_idx"
                    ),
                ],
                "unique_together": {("candidate", "job_posting")},
            },
        ),
    ]
